export interface PhoneCountryCodeOption {
    value: string;
    label: string;
    iso: string;
}

/** Default dial code for new phone rows (India). */
export const DEFAULT_PHONE_COUNTRY_CODE = '+91';

/**
 * Practical dial-code list (one primary country per dial where codes are shared).
 * `value` is the dial prefix stored/merged with the national number.
 */
export const PHONE_COUNTRY_CODES: PhoneCountryCodeOption[] = [
    { value: '+93', label: 'Afghanistan (+93)', iso: 'AF' },
    { value: '+355', label: 'Albania (+355)', iso: 'AL' },
    { value: '+213', label: 'Algeria (+213)', iso: 'DZ' },
    { value: '+376', label: 'Andorra (+376)', iso: 'AD' },
    { value: '+244', label: 'Angola (+244)', iso: 'AO' },
    { value: '+1', label: 'United States / Canada (+1)', iso: 'US' },
    { value: '+54', label: 'Argentina (+54)', iso: 'AR' },
    { value: '+374', label: 'Armenia (+374)', iso: 'AM' },
    { value: '+61', label: 'Australia (+61)', iso: 'AU' },
    { value: '+43', label: 'Austria (+43)', iso: 'AT' },
    { value: '+994', label: 'Azerbaijan (+994)', iso: 'AZ' },
    { value: '+973', label: 'Bahrain (+973)', iso: 'BH' },
    { value: '+880', label: 'Bangladesh (+880)', iso: 'BD' },
    { value: '+375', label: 'Belarus (+375)', iso: 'BY' },
    { value: '+32', label: 'Belgium (+32)', iso: 'BE' },
    { value: '+501', label: 'Belize (+501)', iso: 'BZ' },
    { value: '+229', label: 'Benin (+229)', iso: 'BJ' },
    { value: '+975', label: 'Bhutan (+975)', iso: 'BT' },
    { value: '+591', label: 'Bolivia (+591)', iso: 'BO' },
    { value: '+387', label: 'Bosnia and Herzegovina (+387)', iso: 'BA' },
    { value: '+267', label: 'Botswana (+267)', iso: 'BW' },
    { value: '+55', label: 'Brazil (+55)', iso: 'BR' },
    { value: '+673', label: 'Brunei (+673)', iso: 'BN' },
    { value: '+359', label: 'Bulgaria (+359)', iso: 'BG' },
    { value: '+226', label: 'Burkina Faso (+226)', iso: 'BF' },
    { value: '+257', label: 'Burundi (+257)', iso: 'BI' },
    { value: '+855', label: 'Cambodia (+855)', iso: 'KH' },
    { value: '+237', label: 'Cameroon (+237)', iso: 'CM' },
    { value: '+238', label: 'Cape Verde (+238)', iso: 'CV' },
    { value: '+236', label: 'Central African Republic (+236)', iso: 'CF' },
    { value: '+235', label: 'Chad (+235)', iso: 'TD' },
    { value: '+56', label: 'Chile (+56)', iso: 'CL' },
    { value: '+86', label: 'China (+86)', iso: 'CN' },
    { value: '+57', label: 'Colombia (+57)', iso: 'CO' },
    { value: '+269', label: 'Comoros (+269)', iso: 'KM' },
    { value: '+242', label: 'Congo (+242)', iso: 'CG' },
    { value: '+243', label: 'Congo (DRC) (+243)', iso: 'CD' },
    { value: '+506', label: 'Costa Rica (+506)', iso: 'CR' },
    { value: '+385', label: 'Croatia (+385)', iso: 'HR' },
    { value: '+53', label: 'Cuba (+53)', iso: 'CU' },
    { value: '+357', label: 'Cyprus (+357)', iso: 'CY' },
    { value: '+420', label: 'Czech Republic (+420)', iso: 'CZ' },
    { value: '+45', label: 'Denmark (+45)', iso: 'DK' },
    { value: '+253', label: 'Djibouti (+253)', iso: 'DJ' },
    { value: '+593', label: 'Ecuador (+593)', iso: 'EC' },
    { value: '+20', label: 'Egypt (+20)', iso: 'EG' },
    { value: '+503', label: 'El Salvador (+503)', iso: 'SV' },
    { value: '+240', label: 'Equatorial Guinea (+240)', iso: 'GQ' },
    { value: '+291', label: 'Eritrea (+291)', iso: 'ER' },
    { value: '+372', label: 'Estonia (+372)', iso: 'EE' },
    { value: '+268', label: 'Eswatini (+268)', iso: 'SZ' },
    { value: '+251', label: 'Ethiopia (+251)', iso: 'ET' },
    { value: '+679', label: 'Fiji (+679)', iso: 'FJ' },
    { value: '+358', label: 'Finland (+358)', iso: 'FI' },
    { value: '+33', label: 'France (+33)', iso: 'FR' },
    { value: '+241', label: 'Gabon (+241)', iso: 'GA' },
    { value: '+220', label: 'Gambia (+220)', iso: 'GM' },
    { value: '+995', label: 'Georgia (+995)', iso: 'GE' },
    { value: '+49', label: 'Germany (+49)', iso: 'DE' },
    { value: '+233', label: 'Ghana (+233)', iso: 'GH' },
    { value: '+30', label: 'Greece (+30)', iso: 'GR' },
    { value: '+299', label: 'Greenland (+299)', iso: 'GL' },
    { value: '+502', label: 'Guatemala (+502)', iso: 'GT' },
    { value: '+224', label: 'Guinea (+224)', iso: 'GN' },
    { value: '+245', label: 'Guinea-Bissau (+245)', iso: 'GW' },
    { value: '+592', label: 'Guyana (+592)', iso: 'GY' },
    { value: '+509', label: 'Haiti (+509)', iso: 'HT' },
    { value: '+504', label: 'Honduras (+504)', iso: 'HN' },
    { value: '+852', label: 'Hong Kong (+852)', iso: 'HK' },
    { value: '+36', label: 'Hungary (+36)', iso: 'HU' },
    { value: '+354', label: 'Iceland (+354)', iso: 'IS' },
    { value: '+91', label: 'India (+91)', iso: 'IN' },
    { value: '+62', label: 'Indonesia (+62)', iso: 'ID' },
    { value: '+98', label: 'Iran (+98)', iso: 'IR' },
    { value: '+964', label: 'Iraq (+964)', iso: 'IQ' },
    { value: '+353', label: 'Ireland (+353)', iso: 'IE' },
    { value: '+972', label: 'Israel (+972)', iso: 'IL' },
    { value: '+39', label: 'Italy (+39)', iso: 'IT' },
    { value: '+225', label: 'Ivory Coast (+225)', iso: 'CI' },
    { value: '+81', label: 'Japan (+81)', iso: 'JP' },
    { value: '+962', label: 'Jordan (+962)', iso: 'JO' },
    { value: '+7', label: 'Russia / Kazakhstan (+7)', iso: 'RU' },
    { value: '+254', label: 'Kenya (+254)', iso: 'KE' },
    { value: '+686', label: 'Kiribati (+686)', iso: 'KI' },
    { value: '+965', label: 'Kuwait (+965)', iso: 'KW' },
    { value: '+996', label: 'Kyrgyzstan (+996)', iso: 'KG' },
    { value: '+856', label: 'Laos (+856)', iso: 'LA' },
    { value: '+371', label: 'Latvia (+371)', iso: 'LV' },
    { value: '+961', label: 'Lebanon (+961)', iso: 'LB' },
    { value: '+266', label: 'Lesotho (+266)', iso: 'LS' },
    { value: '+231', label: 'Liberia (+231)', iso: 'LR' },
    { value: '+218', label: 'Libya (+218)', iso: 'LY' },
    { value: '+423', label: 'Liechtenstein (+423)', iso: 'LI' },
    { value: '+370', label: 'Lithuania (+370)', iso: 'LT' },
    { value: '+352', label: 'Luxembourg (+352)', iso: 'LU' },
    { value: '+853', label: 'Macau (+853)', iso: 'MO' },
    { value: '+261', label: 'Madagascar (+261)', iso: 'MG' },
    { value: '+265', label: 'Malawi (+265)', iso: 'MW' },
    { value: '+60', label: 'Malaysia (+60)', iso: 'MY' },
    { value: '+960', label: 'Maldives (+960)', iso: 'MV' },
    { value: '+223', label: 'Mali (+223)', iso: 'ML' },
    { value: '+356', label: 'Malta (+356)', iso: 'MT' },
    { value: '+692', label: 'Marshall Islands (+692)', iso: 'MH' },
    { value: '+222', label: 'Mauritania (+222)', iso: 'MR' },
    { value: '+230', label: 'Mauritius (+230)', iso: 'MU' },
    { value: '+52', label: 'Mexico (+52)', iso: 'MX' },
    { value: '+691', label: 'Micronesia (+691)', iso: 'FM' },
    { value: '+373', label: 'Moldova (+373)', iso: 'MD' },
    { value: '+377', label: 'Monaco (+377)', iso: 'MC' },
    { value: '+976', label: 'Mongolia (+976)', iso: 'MN' },
    { value: '+382', label: 'Montenegro (+382)', iso: 'ME' },
    { value: '+212', label: 'Morocco (+212)', iso: 'MA' },
    { value: '+258', label: 'Mozambique (+258)', iso: 'MZ' },
    { value: '+95', label: 'Myanmar (+95)', iso: 'MM' },
    { value: '+264', label: 'Namibia (+264)', iso: 'NA' },
    { value: '+674', label: 'Nauru (+674)', iso: 'NR' },
    { value: '+977', label: 'Nepal (+977)', iso: 'NP' },
    { value: '+31', label: 'Netherlands (+31)', iso: 'NL' },
    { value: '+64', label: 'New Zealand (+64)', iso: 'NZ' },
    { value: '+505', label: 'Nicaragua (+505)', iso: 'NI' },
    { value: '+227', label: 'Niger (+227)', iso: 'NE' },
    { value: '+234', label: 'Nigeria (+234)', iso: 'NG' },
    { value: '+850', label: 'North Korea (+850)', iso: 'KP' },
    { value: '+389', label: 'North Macedonia (+389)', iso: 'MK' },
    { value: '+47', label: 'Norway (+47)', iso: 'NO' },
    { value: '+968', label: 'Oman (+968)', iso: 'OM' },
    { value: '+92', label: 'Pakistan (+92)', iso: 'PK' },
    { value: '+680', label: 'Palau (+680)', iso: 'PW' },
    { value: '+970', label: 'Palestine (+970)', iso: 'PS' },
    { value: '+507', label: 'Panama (+507)', iso: 'PA' },
    { value: '+675', label: 'Papua New Guinea (+675)', iso: 'PG' },
    { value: '+595', label: 'Paraguay (+595)', iso: 'PY' },
    { value: '+51', label: 'Peru (+51)', iso: 'PE' },
    { value: '+63', label: 'Philippines (+63)', iso: 'PH' },
    { value: '+48', label: 'Poland (+48)', iso: 'PL' },
    { value: '+351', label: 'Portugal (+351)', iso: 'PT' },
    { value: '+974', label: 'Qatar (+974)', iso: 'QA' },
    { value: '+40', label: 'Romania (+40)', iso: 'RO' },
    { value: '+250', label: 'Rwanda (+250)', iso: 'RW' },
    { value: '+1869', label: 'Saint Kitts and Nevis (+1869)', iso: 'KN' },
    { value: '+1758', label: 'Saint Lucia (+1758)', iso: 'LC' },
    { value: '+1784', label: 'Saint Vincent and the Grenadines (+1784)', iso: 'VC' },
    { value: '+685', label: 'Samoa (+685)', iso: 'WS' },
    { value: '+378', label: 'San Marino (+378)', iso: 'SM' },
    { value: '+239', label: 'Sao Tome and Principe (+239)', iso: 'ST' },
    { value: '+966', label: 'Saudi Arabia (+966)', iso: 'SA' },
    { value: '+221', label: 'Senegal (+221)', iso: 'SN' },
    { value: '+381', label: 'Serbia (+381)', iso: 'RS' },
    { value: '+248', label: 'Seychelles (+248)', iso: 'SC' },
    { value: '+232', label: 'Sierra Leone (+232)', iso: 'SL' },
    { value: '+65', label: 'Singapore (+65)', iso: 'SG' },
    { value: '+421', label: 'Slovakia (+421)', iso: 'SK' },
    { value: '+386', label: 'Slovenia (+386)', iso: 'SI' },
    { value: '+677', label: 'Solomon Islands (+677)', iso: 'SB' },
    { value: '+252', label: 'Somalia (+252)', iso: 'SO' },
    { value: '+27', label: 'South Africa (+27)', iso: 'ZA' },
    { value: '+82', label: 'South Korea (+82)', iso: 'KR' },
    { value: '+211', label: 'South Sudan (+211)', iso: 'SS' },
    { value: '+34', label: 'Spain (+34)', iso: 'ES' },
    { value: '+94', label: 'Sri Lanka (+94)', iso: 'LK' },
    { value: '+249', label: 'Sudan (+249)', iso: 'SD' },
    { value: '+597', label: 'Suriname (+597)', iso: 'SR' },
    { value: '+46', label: 'Sweden (+46)', iso: 'SE' },
    { value: '+41', label: 'Switzerland (+41)', iso: 'CH' },
    { value: '+963', label: 'Syria (+963)', iso: 'SY' },
    { value: '+886', label: 'Taiwan (+886)', iso: 'TW' },
    { value: '+992', label: 'Tajikistan (+992)', iso: 'TJ' },
    { value: '+255', label: 'Tanzania (+255)', iso: 'TZ' },
    { value: '+66', label: 'Thailand (+66)', iso: 'TH' },
    { value: '+670', label: 'Timor-Leste (+670)', iso: 'TL' },
    { value: '+228', label: 'Togo (+228)', iso: 'TG' },
    { value: '+676', label: 'Tonga (+676)', iso: 'TO' },
    { value: '+1868', label: 'Trinidad and Tobago (+1868)', iso: 'TT' },
    { value: '+216', label: 'Tunisia (+216)', iso: 'TN' },
    { value: '+90', label: 'Turkey (+90)', iso: 'TR' },
    { value: '+993', label: 'Turkmenistan (+993)', iso: 'TM' },
    { value: '+688', label: 'Tuvalu (+688)', iso: 'TV' },
    { value: '+256', label: 'Uganda (+256)', iso: 'UG' },
    { value: '+380', label: 'Ukraine (+380)', iso: 'UA' },
    { value: '+971', label: 'United Arab Emirates (+971)', iso: 'AE' },
    { value: '+44', label: 'United Kingdom (+44)', iso: 'GB' },
    { value: '+598', label: 'Uruguay (+598)', iso: 'UY' },
    { value: '+998', label: 'Uzbekistan (+998)', iso: 'UZ' },
    { value: '+678', label: 'Vanuatu (+678)', iso: 'VU' },
    { value: '+379', label: 'Vatican City (+379)', iso: 'VA' },
    { value: '+58', label: 'Venezuela (+58)', iso: 'VE' },
    { value: '+84', label: 'Vietnam (+84)', iso: 'VN' },
    { value: '+967', label: 'Yemen (+967)', iso: 'YE' },
    { value: '+260', label: 'Zambia (+260)', iso: 'ZM' },
    { value: '+263', label: 'Zimbabwe (+263)', iso: 'ZW' },
];

/** Options shaped for Select2Wrapper / react-select. */
export const PHONE_COUNTRY_CODE_OPTIONS = PHONE_COUNTRY_CODES.map(({ value, label }) => ({
    value,
    label,
}));

const DIAL_TO_ISO = new Map(PHONE_COUNTRY_CODES.map((c) => [c.value, c.iso]));

/** Dial codes sorted longest-first for prefix matching. */
export const PHONE_DIAL_CODES_BY_LENGTH = [...new Set(PHONE_COUNTRY_CODES.map((c) => c.value))].sort(
    (a, b) => b.length - a.length,
);

export function getIsoForDialCode(dialCode: string): string | undefined {
    return DIAL_TO_ISO.get(dialCode);
}

/** Flag image URL (avoids Windows emoji falling back to ISO letters like "IN"). */
export function getFlagImageUrl(iso: string, width = 20): string {
    return `https://flagcdn.com/w${width}/${iso.trim().toLowerCase()}.png`;
}
